CREATE TABLE infirmiere
(
	idInfirmiere INT,
	nomInfirmiere VARCHAR(38),
	prenomInfirmiere VARCHAR(38),
	LOGININF VARCHAR(50) NOT NULL,
	PASSINF VARCHAR(15) NOT NULL,
	PRIMARY KEY (IDINF)
);

CREATE TABLE patient
(
    IDPATIENT INT NOT NULL,
	NOMPATIENT VARCHAR(38),
    PRENOMPATIENT VARCHAR(38),
    INSEEPATIENT VARCHAR(15),
	PATHOPATIENT VARCHAR(50),
    DATEPATIENT VARCHAR(11),
    ACTIFPATIENT BOOLEAN,
	IDINFPATIENT,
	PRIMARY KEY (IDPATIENT)
);

CREATE TABLE utilisateur
(
	idUtilisateur int NOT NULL ,
	loginPatient VARCHAR(40),
	passwordPatient VARCHAR(40),
	PRIMARY KEY (idPatient)
);
	
	
